### ISSUE TITLE
초기 화면 하단 기업 목록 슬라이드 코드 정리

### ISSUE THREAD

**Issue by mozodev** [creativecommonskorea/sharehub_2015_en#6]
yaml 코드 추가에 따라 변수명 수정

**Comment by khseo** [comment]
각 카테고리 별로 업데이트된 14개 기업들 로고 이미지들 첨부해요~

png, jpg 등 확장자는 다양하지만 150x150px로 모두 맞추었어요.

제 나름대로는 열심히 14개 기업들 추가했는데 오류가 없기를 바래요..^ ^;;
- 서경희  _Kyeong Hee, Seo_[image: cckorea_logo3.png]*
  
  CCKOREA | 매니저 Manager

_오픈과 공유의 가치를 믿으시나요? CCKOREA 후원 회원이 되어주세요! (-> 회원가입하기
http://cckorea.org/xe/?mid=join_members)_

_Tel_ 070-7618-0321  _Mobile_ +82 (0)10-2683-8432 _Fax_ 070-7618-0234

*Address *서울시 마포구 서교동 363-20 5층  (오시는길 http://cckorea.org/xe/contactus)

_Sites  CCKOREA_ (cc http://cckorea.org/korea.org http://cckorea.org/) ㅣ
_공유허브 *(_sharehub.kr http://sharehub.kr/_) ㅣ_코드나무 _(_codenamu.org
http://codenamu.org/*)

2015-07-09 10:40 GMT+09:00 Yeongtaek Hong notifications@github.com:

**Comment by khseo** [comment]
@mozodev 저는 Sharing City Seoul 메뉴에 2015 Excutive Summary 링크가 보이지 않네요...ㅠ 확인 부탁드려요!

**Comment by mozodev** [comment]
혹시 그런 증상이 있으면 캐시때문이니까 다른 브라우저로 보시던가 캐시를 삭제하고 다시 로드하셔야 합니다.

**Comment by nanshil** [comment]
@mozodev @khseo 
확인했습니다~ 수고 많으셨어요!
